### ISSUE TITLE
Problems with alternate subnet masks?

### ISSUE THREAD

**Issue by OttoWerse** [comroid-git/VBAN-API-CS#1]
I recently acquired a stream deck mini for controlling Voicemeeter on my audio server as well as my main PC. Since I wanted just one StreamDeck, I need to send VBAN-TEXT commands from the server to the desktop, this is where I came across this interesting (and potentially very useful) plugin. However, I'm having difficulties getting it to work. 

For a quick test, I have copied the following code from an already set up (and confirmed working) Macro.Buttons button to a VBANDeck SimpleScript Action.

IP-Adress:`192.169.1.10`
Port:`6980`
Script:`BEGIN_SECTION("vban1")
Strip(0).mute=1;
END_SECTION`

But it doesn't seem to work with the plugin, the StreamDeck simply displays a big, yellow warning triangle above the button, and nothing else happens.

My only good guess is that this might be caused by my subnet mask since others have reported this plugin to be working fine. As I'm in an environment with more than 255 clients on the network, I am forced to use a 255.255.0.0 subnet mask. Our networking setup also forced us to use the 192.169.X.X subnet, since the default 192.168.X.X subnet is taken by infrastructure devices. This might cause some issues with the networking code if it is not built to handle this.

Otherwise, it might also be caused by windows firewall, as I don't know if the plugin requires any additional ports to be opened up. But since I have already got VBAN commands set up and running within Voicemeeter Potato and allowed the StreamDeck application to conduct incoming and outgoing traffic, I wouldn't know what is missing. (if this is the case, maybe add them to a Readme file, so this question doesn't come up again in the future)

I hope this issue can be resolved soon, so I can use my StreamDeck to its full potential.

**Comment by OttoWerse** [comment]
Sorry for the late response, I didn't have desktop access to the machine in question before. Anyways I took at the log file after pressing the buttons I have set up, it seems everytime a VBANDeck button is pressed, the plugin hangs up and gets terminated by the StreamDeck itself. These log-section always look like this:
`22:57:31.494                     StreamDeck                        ESDActionsGridViewModel::onKeyPressed():        emit keyPressed idx: 1`
`22:57:31.597                     StreamDeck                        ESDActionsGridViewModel::onKeyReleased():       emit keyReleased idx: 1`
`22:58:16.152                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_98961b8ad78863a54a818ca5e28f2dfe>::()::<lambda_8f70ed91ccac7ade1a52db0413d1ea8a>::operator ()(): Restarting plugin 'VBANDeck' after one minute`
`22:58:16.331                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_98961b8ad78863a54a818ca5e28f2dfe>::operator ()(): The plugin 'VBANDeck' crashed with code 1:-2147450740`
`22:58:16.331                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_98961b8ad78863a54a818ca5e28f2dfe>::operator ()(): Restarting plugin 'VBANDeck'`
`22:58:16.483                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_98961b8ad78863a54a818ca5e28f2dfe>::operator ()(): The plugin 'VBANDeck' crashed with code 1:-2147450740`

The Error code also seems to be the same regardless of the type of button. Sometimes (strangely not always) there are these log-entires in between the failed restarts:

`22:56:18.576                     StreamDeck                        ESDCustomPluginCommunication::onMessageReceived(): PI A61E1C0279D352A828A55688E98B18A5 is now connected`
`22:56:18.577                     StreamDeck                        ESDCustomPlugin::SendJSON():                    Could not send json because the plugin is not registered`
`22:56:18.578                     StreamDeck                        ESDCustomPlugin::SendJSON():                    Could not send json because the plugin is not registered`

I don't want to read too much into this, but "could not send json because the plugin is not registered" sounds like something else than a networking problem to me, maybe the plugin is just not properly installed? I did some googling and found other threads where people talk about this error appearing in other plugins but haven't found any solutions yet. I hope this helps.

**Comment by burdoto** [comment]
Hey, thanks for the logs. Although I will need the complete log file that you find at `%appdata%\Elgato\StreamDeck\Plugins\de.kaleidox.vbandeck.sdPlugin\pluginlog.log`, there is something that you can do now:
You should try to use the `tracert` tool to try to trace your way into your VoiceMeeter-PC and share the anonymized output of that here. (`tracert 192.169.1.10`)
Thanks!

**Comment by OttoWerse** [comment]
I can't seem to find any log files inside the folder of the plugin, unfortunately, are they supposed to always be there, or do they only get created, once something (of the desired logging level) is logged?

When tracing the route from my server to my desktop (or vice versa) they only pass through one router, as they are on the same subnet. (192.169.X.X)

`Tracing route to Jupiter.fritz.box [192.169.0.201]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  Jupiter.fritz.box [192.169.0.201]

Trace complete.`

**Comment by burdoto** [comment]
Hello @OttoWerse,
I have just recently published a preliminary update for VBANDeck [to GitHub here](https://github.com/burdoto/VBANDeck/releases/tag/1.0.1), which will bump the dependencies to always create the beforementioned `pluginlog.log` file.
I would highly appreciate if you could try using this release with your known-bad settings and then sharing your complete `pluginlog.log` file as requested before in this issue.
Also, you are sincerely invited to join [realBarRaider's Discord server](http://discord.BarRaider.com) which functions as a "community hub" for Plugins made for the Elgato StreamDeck. You can mention me there under the Discord tag `@Kaleidox#0001`, and you are welcome to send the file over there.

**Comment by burdoto** [comment]
Moved to https://youtrack.comroid.de/issue/VB-1.
